#
#  Copyright 2024 Winford <winford@object.stream>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: "Check Erlang formatting"

on:
  push:
    paths:
      - '.github/workflows/erlfmt.yaml'
      - '**/*.erl'
      - '**/*.hrl'
  pull_request:
    paths:
      - '.github/workflows/erlfmt.yaml'
      - '**/*.hrl'
      - '**/*.erl'

jobs:
  erlang-format-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - uses: erlef/setup-beam@v1
      with:
        otp-version: 24.3
        elixir-version: 1.12

    - name: "Check formatting with rebar3 fmt"
      run: |
        rebar3 as check fmt -c
